### ISSUE TITLE
no README

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Web-Report#1]
Thanks for mentioning this repo in today's [Dataverse Community Call](https://groups.google.com/d/msg/dataverse-community/WlENLGH9yJM/Y9ALifdBAAAJ).

I noticed there's no README. When you add it, can you please mention how the the data that this web report operates on is generated? I assume the data comes from code over at https://github.com/scholarsportal/Dataverse_Report

**Comment by kevinworthington** [comment]
Hi @pdurbin, 
Thanks for your suggestion. A README file has been added!
